// #pragma once

// #ifndef RAZ_RAZ_HPP
// #define RAZ_RAZ_HPP

// #include "Application.hpp"
// #include "Component.hpp"
// #include "Entity.hpp"
// #include "System.hpp"
// #include "World.hpp"
// #include "Animation/Skeleton.hpp"
// #include "Audio/AudioData.hpp"
// #include "Audio/AudioSystem.hpp"
// #include "Audio/AudioUtils.hpp"
// #include "Audio/Listener.hpp"
// #include "Audio/Microphone.hpp"
// #include "Audio/Sound.hpp"
// #include "Audio/SoundEffect.hpp"
// #include "Audio/SoundEffectSlot.hpp"
// #include "Data/Bitset.hpp"
// #include "Data/BoundingVolumeHierarchy.hpp"
// #include "Data/BoundingVolumeHierarchySystem.hpp"
// #include "Data/BvhFormat.hpp"
// #include "Data/Color.hpp"
// #include "Data/FbxFormat.hpp"
// #include "Data/GltfFormat.hpp"
// #include "Data/Graph.hpp"
// #include "Data/Image.hpp"
// #include "Data/ImageFormat.hpp"
// #include "Data/Mesh.hpp"
// #include "Data/MeshDistanceField.hpp"
// #include "Data/MeshFormat.hpp"
// #include "Data/ObjFormat.hpp"
// #include "Data/OffFormat.hpp"
// #include "Data/Submesh.hpp"
// #include "Data/TgaFormat.hpp"
// #include "Data/WavFormat.hpp"
// #include "Math/Angle.hpp"
// #include "Math/Constants.hpp"
// #include "Math/MathUtils.hpp"
// #include "Math/Matrix.hpp"
// #include "Math/PerlinNoise.hpp"
// #include "Math/Quaternion.hpp"
// #include "Math/Transform.hpp"
// #include "Math/Vector.hpp"
// #include "PhysicsSystem/Collider.hpp"
// #include "PhysicsSystem/PhysicsSystemSystem.hpp"
// #include "PhysicsSystem/RigidBody.hpp"
// #include "render/process/bloom.hpp>
// #include "render/process/box_blur.hpp>
// #include "render/Camera.hpp"
// #include "render/CannyFilter.hpp"
// #include "render//process/chromatic_aberration.hpp>
// #include "render/ConvolutionRenderProcess.hpp"
// #include "render/Cubemap.hpp"
// #include "render/process/film_grain.hpp>
// #include "render/Framebuffer.hpp"
// #include "render/process/gaussian_blur.hpp>
// #include "render/GraphicObjects.hpp"
// #include "render/Light.hpp"
// #include "render/Material.hpp"
// #include "render/Meshrenderer.hpp>
// #include "render/process/mono_pass.hpp>
// #include "render/Overlay.hpp"
// #include "render/Pixelization.hpp"
// #include "render/renderer.hpp>
// #include "render/render_graph.hpp>
// #include "render/process/render_pass.hpp>
// #include "render/process/render_process.hpp>
// #include "render/RenderSystem.hpp"
// #include "render/process/ssr.hpp>
// #include "render/shader.hpp>
// #include "render/ShaderProgram.hpp"
// #include "render/SobelFilter.hpp"
// #include "render/Submeshrenderer.hpp>
// #include "render/texture.hpp>
// #include "render/platform/uniform_buffer.hpp>
// #include "render/process/vignette.hpp>
// #include "render/Window.hpp"
// #include "Script/LuaEnvironment.hpp"
// #include "Script/LuaScript.hpp"
// #include "Script/LuaWrapper.hpp"
// #include "Script/ScriptSystem.hpp"
// #include "Utils/CompilerUtils.hpp"
// #include "Utils/EnumUtils.hpp"
// #include "Utils/FilePath.hpp"
// #include "Utils/FileUtils.hpp"
// #include "Utils/FloatUtils.hpp"
// #include "Utils/Input.hpp"
// #include "Utils/Logger.hpp"
// #include "Utils/Plugin.hpp"
// #include "Utils/Ray.hpp"
// #include "Utils/Shape.hpp"
// #include "Utils/StrUtils.hpp"
// #include "Utils/Threading.hpp"
// #include "Utils/ThreadPool.hpp"
// #include "Utils/TriggerSystem.hpp"
// #include "Utils/TriggerVolume.hpp"
// #include "Utils/TypeUtils.hpp"
// #include "XR/XrContext.hpp"
// #include "XR/XrSession.hpp"
// #include "XR/XrSystem.hpp"

// using namespace Raz::Literals;

// #endif // RAZ_RAZ_HPP
